import { useQuery } from "@tanstack/react-query";
import Blogs from "components/Blogs";
import Hero from "components/Hero";
import TechStack from "components/TechStack";
import Work from "components/Work";
import Head from "next/head";
import { getArticles } from "services/article";

export default function Home({ articles }: TArticles) {
  const { data, isFetching, error } = useQuery<TResponse, Error>({
    queryKey: ["articles"],
    queryFn: getArticles,
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <TechStack />
        <Work />
        <Blogs articles={articles} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: { articles: await getArticles() },
  };
};
